### ISSUE TITLE
Time to train

### ISSUE THREAD

**Issue by crepejung00** [henry123-boy/Level-S2FM_official#19]
Hi,
Thank you for sharing your awesome work!

Could you please share how much time it took to train the full network and the hardware you used?
I couldn't find any additional explanation about the training time or hardware.

Thanks!

**Comment by BruceLz** [comment]
Hey, bro, have you ever tried training and timing?

**Comment by henry123-boy** [comment]
Hey, thank you guys for put attention on our work. Meanwhile, I feel sorry for not being reply the issues in time. Here is the answer for those questions above.

- The training time: our algorithm is one of the incremental SfM, where the training time is up to the total number of scenes images. For example, in Scan65, DTU the total training time is around 10 hours for 49 images in a single GPU 2080 Ti. 
- Speeding up the training is on our **TODO lists**
- Setting to reduce the training time: If you can not bear so long training time, you can use the setting that close the SDF-base Triangulation (Traditional Triangulation + Neural Bundle Adjustment). The drop of Precise is bearable, which was reported in the ablation study in our paper.
