### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by amughrabi** [henry123-boy/Level-S2FM_official#20]
Hi,
Very interesting work, thanks for open-sourcing the code. I downloaded the data and I run the following command:

```bash
python train.py --group=DTU --pipeline=LevelS2fM --yaml=DTU --name=65_dual --data.dataset=DTU --data.scene=scan65   --sfm_mode=full  --Ablate_config.dual_field=true
```

The training generates `00000045.ply`, and I saw the following error:
```
Traceback (most recent call last):                                                                                                              
  File "/media/HDD_2TB/amughrabi/projects/Level-S2FM_official/train.py", line 23, in <module>
    main()
  File "/media/HDD_2TB/amughrabi/projects/Level-S2FM_official/train.py", line 20, in main
    m.train(opt)
  File "/media/HDD_2TB/amughrabi/projects/Level-S2FM_official/pipelines/LevelS2fM.py", line 245, in train
    new_id = pose_graph_left[0]
IndexError: list index out of range
```

Would you please advise?

**Comment by henry123-boy** [comment]
Hi, thank you for being interested in our project. And I am a little bit confused about the problem, cause we had tested this code in DTU65 before, and in https://github.com/henry123-boy/Level-S2FM_official/blob/main/pipelines/LevelS2fM.py#L238
if the `pose_graph_left` is empty list, the whole algorithm will be finished and terminated.

**Comment by amughrabi** [comment]
> Hi, thank you for being interested in our project. And I am a little bit confused about the problem, cause we had tested this code in DTU65 before, and in https://github.com/henry123-boy/Level-S2FM_official/blob/main/pipelines/LevelS2fM.py#L238
> if the `pose_graph_left` is empty list, the whole algorithm will be finished and terminated.

AFAICT, after `print(f"finish!")`, a program termination should follow the statement. e.g., "sys.exit()" unless we have some data to store after it.

**Comment by leo-frank** [comment]
I think we should add something like` "sys.exit()" `after `print(f"finish!") `https://github.com/henry123-boy/Level-S2FM_official/blob/main/pipelines/LevelS2fM.py#L238 for normal program exit.
